name: CI

on: [push]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      # check out repo and set up python
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      # install poetry
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.1.12"
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/.venv
          installer-parallel: true

      # use cache if possible
      - name: Load cached venv
        id: cached-poetry-venv
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      # install the project
      - name: Install project
        run: poetry install --no-interaction

      # check code has been formatted correctly
      - name: Check formatting
        run: poetry run black . --check

      # check code passes mypy
      - name: Run linting & type checking
        run: poetry run mypy .

      # check tests pass
      - name: Test project
        run: poetry run pytest -v
