name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # check out repo and set up python
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # install poetry
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.1.12"
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/venv
          installer-parallel: true

      # some stuff can be done with caching to speed up if needed

      # install project
      - name: Install project
        run: poetry install --no-interaction

      # check code has been formatted correctly
      - name: Check formatting
        run: poetry run black . --check

      # check code passes pylint and mypy
      # TODO

      # check tests pass
      - name: Test project
        run: poetry run pytest
