# This is a basic workflow to help you get started with Actions

name: noah-remote

# Controls when the workflow will run
on:
  [push]
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  #push:
   # branches: [ $default-branch ]
  # pull_request:
  #   branches: [ $default-branch ]

  # Allows you to run this workflow manually from the Actions tab


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # SSH into digitalocean droplet
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}




      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd ~/SoftEng-Project,
          git pull,
          poetry shell
          poetry install
          

      
